language: python
services:
- docker
before_install:
- export DELTA_PATH=`pwd`; echo $DELTA_PATH
- export DOCKER_DELTA="/home/gitlab-runner/delta"; echo $DOCKER_DELTA
- export CI_IMAGE=zh794390558/delta:ci-cpu-py3
- docker pull ${CI_IMAGE}
- docker run -it -d --name travis_con --user root -v ${DELTA_PATH}:${DOCKER_DELTA}
  ${CI_IMAGE} bash
- docker exec travis_con bash -c "gcc -v && g++ -v"
- docker exec travis_con bash -c "cd ${DOCKER_DELTA}; source env.sh"
- docker exec travis_con bash -c "cd ${DOCKER_DELTA}/tools; make basic check_install"
- docker exec travis_con bash -c "cd ${DOCKER_DELTA}/tools/install; bash prepare_kaldi.sh"
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
jobs:
  include:
  - stage: test
    script: docker exec travis_con bash -c "cd ${DOCKER_DELTA}; bash tools/test/python_test.sh"
  - script: docker exec travis_con bash -c "cd ${DOCKER_DELTA}; bash tools/test/lint.sh"
before_script:
- bash test_mypy.sh
script:
- echo "SCRIPT SECTION"
